class_name upgrades_utils extends Node

enum upgrades {
	BALL_BOUNCE_UP,
	BALL_BOUNCE_DOWN,
	BALL_SIZE_UP,
	BALL_SIZE_DOWN,
	BALL_DAMAGE_TO_ENEMIES_UP,
	BALL_DAMAGE_TO_ENEMIES_DOWN,
	BALL_DAMAGE_TO_STRUCTURES_UP,
	BALL_DAMAGE_TO_STRUCTURES_DOWN,
	BALL_DAMAGE_TO_BOSSES_UP,
	BALL_DAMAGE_TO_BOSSES_DOWN,
	BALL_DAMAGE_UP,
	BALL_DAMAGE_DOWN,
	BALL_ELEMENTAL_DAMAGE_UP,
	BALL_ELEMENTAL_DAMAGE_DOWN,
	BALL_KNOCKBACK_UP,
	BALL_KNOCKBACK_DOWN,
	BALL_CRITICAL_HIT_CHANCE_UP,
	BALL_CRITICAL_HIT_CHANCE_DOWN,
	BALL_HEALTH_UP,
	BALL_HEALTH_DOWN,
	BALL_HEALTH_REGEN_UP,
	BALL_HEALTH_REGEN_DOWN,
	FLIPPER_SPEED_UP,
	FLIPPER_SPEED_DOWN,
	FLIPPER_PRECISION_UP,
	FLIPPER_PRECISION_DOWN,
	BUMPER_EXPANSION_SPEED_UP,
	BUMPER_EXPANSION_SPEED_DOWN,
	BUMPER_PRECISION_UP,
	BUMPER_PRECISION_DOWN,
	XP_GAIN_UP,
	XP_GAIN_DOWN,
	PICKUP_RANGE_UP,
	PICKUP_RANGE_DOWN,
	ITEMS_DISCOUNT_UP,
	ITEMS_DISCOUNT_DOWN,
	EXPLOSION_DAMAGE_UP,
	EXPLOSION_DAMAGE_DOWN,
	EXPLOSION_RADIUS_UP,
	EXPLOSION_RADIUS_DOWN,
	PIERCING_UP,
	PIERCING_DOWN,
	FREE_REROLL_UP,
	FREE_REROLL_DOWN,
	LUCK_UP,
	LUCK_DOWN,
	REMAINING_BALLS_UP,
	REMAINING_BALLS_DOWN,
	MAX_BALLS_UP,
	MAX_BALLS_DOWN
}

const UPGRADE_NAMES = {
	upgrades.BALL_BOUNCE_UP: "Ball Bounce Up",
	upgrades.BALL_BOUNCE_DOWN: "Ball Bounce Down",
	upgrades.BALL_SIZE_UP: "Ball Size Up",
	upgrades.BALL_SIZE_DOWN: "Ball Size Down",
	upgrades.BALL_DAMAGE_TO_ENEMIES_UP: "Ball Damage to Enemies Up",
	upgrades.BALL_DAMAGE_TO_ENEMIES_DOWN: "Ball Damage to Enemies Down",
	upgrades.BALL_DAMAGE_TO_STRUCTURES_UP: "Ball Damage to Structures Up",
	upgrades.BALL_DAMAGE_TO_STRUCTURES_DOWN: "Ball Damage to Structures Down",
	upgrades.BALL_DAMAGE_TO_BOSSES_UP: "Ball Damage to Bosses Up",
	upgrades.BALL_DAMAGE_TO_BOSSES_DOWN: "Ball Damage to Bosses Down",
	upgrades.BALL_DAMAGE_UP: "Ball Damage Up",
	upgrades.BALL_DAMAGE_DOWN: "Ball Damage Down",
	upgrades.BALL_ELEMENTAL_DAMAGE_UP: "Ball Elemental Damage Up",
	upgrades.BALL_ELEMENTAL_DAMAGE_DOWN: "Ball Elemental Damage Down",
	upgrades.BALL_KNOCKBACK_UP: "Ball Knockback Up",
	upgrades.BALL_KNOCKBACK_DOWN: "Ball Knockback Down",
	upgrades.BALL_CRITICAL_HIT_CHANCE_UP: "Ball Critical Hit Chance Up",
	upgrades.BALL_CRITICAL_HIT_CHANCE_DOWN: "Ball Critical Hit Chance Down",
	upgrades.BALL_HEALTH_UP: "Ball Health Up",
	upgrades.BALL_HEALTH_DOWN: "Ball Health Down",
	upgrades.BALL_HEALTH_REGEN_UP: "Ball Health Regen Up",
	upgrades.BALL_HEALTH_REGEN_DOWN: "Ball Health Regen Down",
	upgrades.FLIPPER_SPEED_UP: "Flipper Speed Up",
	upgrades.FLIPPER_SPEED_DOWN: "Flipper Speed Down",
	upgrades.FLIPPER_PRECISION_UP: "Flipper Precision Up",
	upgrades.FLIPPER_PRECISION_DOWN: "Flipper Precision Down",
	upgrades.BUMPER_EXPANSION_SPEED_UP: "Bumper Expansion Speed Up",
	upgrades.BUMPER_EXPANSION_SPEED_DOWN: "Bumper Expansion Speed Down",
	upgrades.BUMPER_PRECISION_UP: "Bumper Precision Up",
	upgrades.BUMPER_PRECISION_DOWN: "Bumper Precision Down",
	upgrades.XP_GAIN_UP: "XP Gain Up",
	upgrades.XP_GAIN_DOWN: "XP Gain Down",
	upgrades.PICKUP_RANGE_UP: "Pickup Range Up",
	upgrades.PICKUP_RANGE_DOWN: "Pickup Range Down",
	upgrades.ITEMS_DISCOUNT_UP: "Items Discount Up",
	upgrades.ITEMS_DISCOUNT_DOWN: "Items Discount Down",
	upgrades.EXPLOSION_DAMAGE_UP: "Explosion Damage Up",
	upgrades.EXPLOSION_DAMAGE_DOWN: "Explosion Damage Down",
	upgrades.EXPLOSION_RADIUS_UP: "Explosion Radius Up",
	upgrades.EXPLOSION_RADIUS_DOWN: "Explosion Radius Down",
	upgrades.PIERCING_UP: "Piercing Up",
	upgrades.PIERCING_DOWN: "Piercing Down",
	upgrades.FREE_REROLL_UP: "Free Reroll Up",
	upgrades.FREE_REROLL_DOWN: "Free Reroll Down",
	upgrades.LUCK_UP: "Luck Up",
	upgrades.LUCK_DOWN: "Luck Down",
	upgrades.REMAINING_BALLS_UP: "Remaining Balls Up",
	upgrades.REMAINING_BALLS_DOWN: "Remaining Balls Down",
	upgrades.MAX_BALLS_UP: "Max Balls Up",
	upgrades.MAX_BALLS_DOWN: "Max Balls Down"
}

const UPGRADE_DESCRIPTIONS = {
	upgrades.BALL_BOUNCE_UP: "Increases the bounce of the ball.",
	upgrades.BALL_BOUNCE_DOWN: "Decreases the bounce of the ball.",
	upgrades.BALL_SIZE_UP: "Increases the size of the ball.",
	upgrades.BALL_SIZE_DOWN: "Decreases the size of the ball.",
	upgrades.BALL_DAMAGE_TO_ENEMIES_UP: "Increases damage to enemies.",
	upgrades.BALL_DAMAGE_TO_ENEMIES_DOWN: "Decreases damage to enemies.",
	upgrades.BALL_DAMAGE_TO_STRUCTURES_UP: "Increases damage to structures.",
	upgrades.BALL_DAMAGE_TO_STRUCTURES_DOWN: "Decreases damage to structures.",
	upgrades.BALL_DAMAGE_TO_BOSSES_UP: "Increases damage to bosses.",
	upgrades.BALL_DAMAGE_TO_BOSSES_DOWN: "Decreases damage to bosses.",
	upgrades.BALL_DAMAGE_UP: "Increases overall ball damage.",
	upgrades.BALL_DAMAGE_DOWN: "Decreases overall ball damage.",
	upgrades.BALL_ELEMENTAL_DAMAGE_UP: "Increases elemental damage of the ball.",
	upgrades.BALL_ELEMENTAL_DAMAGE_DOWN: "Decreases elemental damage of the ball.",
	upgrades.BALL_KNOCKBACK_UP: "Increases knockback effect of the ball.",
	upgrades.BALL_KNOCKBACK_DOWN: "Decreases knockback effect of the ball.",
	upgrades.BALL_CRITICAL_HIT_CHANCE_UP: "Increases critical hit chance of the ball.",
	upgrades.BALL_CRITICAL_HIT_CHANCE_DOWN: "Decreases critical hit chance of the ball.",
	upgrades.BALL_HEALTH_UP: "Increases health of the ball.",
	upgrades.BALL_HEALTH_DOWN: "Decreases health of the ball.",
	upgrades.BALL_HEALTH_REGEN_UP: "Increases health regeneration of the ball.",
	upgrades.BALL_HEALTH_REGEN_DOWN: "Decreases health regeneration of the ball.",
	upgrades.FLIPPER_SPEED_UP: "Increases speed of the flipper.",
	upgrades.FLIPPER_SPEED_DOWN: "Decreases speed of the flipper.",
	upgrades.FLIPPER_PRECISION_UP: "Increases precision of the flipper.",
	upgrades.FLIPPER_PRECISION_DOWN: "Decreases precision of the flipper.",
	upgrades.BUMPER_EXPANSION_SPEED_UP: "Increases expansion speed of the bumper.",
	upgrades.BUMPER_EXPANSION_SPEED_DOWN: "Decreases expansion speed of the bumper.",
	upgrades.BUMPER_PRECISION_UP: "Increases precision of the bumper.",
	upgrades.BUMPER_PRECISION_DOWN: "Decreases precision of the bumper.",
	upgrades.XP_GAIN_UP: "Increases XP gain.",
	upgrades.XP_GAIN_DOWN: "Decreases XP gain.",
	upgrades.PICKUP_RANGE_UP: "Increases pickup range.",
	upgrades.PICKUP_RANGE_DOWN: "Decreases pickup range.",
	upgrades.ITEMS_DISCOUNT_UP: "Increases item discount.",
	upgrades.ITEMS_DISCOUNT_DOWN: "Decreases item discount.",
	upgrades.EXPLOSION_DAMAGE_UP: "Increases explosion damage.",
	upgrades.EXPLOSION_DAMAGE_DOWN: "Decreases explosion damage.",
	upgrades.EXPLOSION_RADIUS_UP: "Increases explosion radius.",
	upgrades.EXPLOSION_RADIUS_DOWN: "Decreases explosion radius.",
	upgrades.PIERCING_UP: "Increases piercing effect.",
	upgrades.PIERCING_DOWN: "Decreases piercing effect.",
	upgrades.FREE_REROLL_UP: "Increases free reroll chance.",
	upgrades.FREE_REROLL_DOWN: "Decreases free reroll chance.",
	upgrades.LUCK_UP: "Increases luck.",
	upgrades.LUCK_DOWN: "Decreases luck.",
	upgrades.REMAINING_BALLS_UP: "Increases remaining balls.",
	upgrades.REMAINING_BALLS_DOWN: "Decreases remaining balls.",
	upgrades.MAX_BALLS_UP: "Increases maximum balls.",
	upgrades.MAX_BALLS_DOWN: "Decreases maximum balls."
}

const UPGRADE_VALUES = {
	upgrades.BALL_BOUNCE_UP: 0.2,
	upgrades.BALL_BOUNCE_DOWN: -0.2,
	upgrades.BALL_SIZE_UP: 1,
	upgrades.BALL_SIZE_DOWN: -1,
	upgrades.BALL_DAMAGE_TO_ENEMIES_UP: 0.1,
	upgrades.BALL_DAMAGE_TO_ENEMIES_DOWN: -0.1,
	upgrades.BALL_DAMAGE_TO_STRUCTURES_UP: 0.1,
	upgrades.BALL_DAMAGE_TO_STRUCTURES_DOWN: -0.1,
	upgrades.BALL_DAMAGE_TO_BOSSES_UP: 0.1,
	upgrades.BALL_DAMAGE_TO_BOSSES_DOWN: -0.1,
	upgrades.BALL_DAMAGE_UP: 10,
	upgrades.BALL_DAMAGE_DOWN: -10,
	upgrades.BALL_ELEMENTAL_DAMAGE_UP: 5,
	upgrades.BALL_ELEMENTAL_DAMAGE_DOWN: -5,
	upgrades.BALL_KNOCKBACK_UP: 10,
	upgrades.BALL_KNOCKBACK_DOWN: -10,
	upgrades.BALL_CRITICAL_HIT_CHANCE_UP: 5,
	upgrades.BALL_CRITICAL_HIT_CHANCE_DOWN: -5,
	upgrades.BALL_HEALTH_UP: 100,
	upgrades.BALL_HEALTH_DOWN: -100,
	upgrades.BALL_HEALTH_REGEN_UP: 0.5,
	upgrades.BALL_HEALTH_REGEN_DOWN: -0.5,
	upgrades.FLIPPER_SPEED_UP: 0.2,
	upgrades.FLIPPER_SPEED_DOWN: -0.2,
	upgrades.FLIPPER_PRECISION_UP: 0.2,
	upgrades.FLIPPER_PRECISION_DOWN: -0.2,
	upgrades.BUMPER_EXPANSION_SPEED_UP: 0.2,
	upgrades.BUMPER_EXPANSION_SPEED_DOWN: -0.2,
	upgrades.BUMPER_PRECISION_UP: 0.2,      
	upgrades.BUMPER_PRECISION_DOWN: -0.2,
	upgrades.XP_GAIN_UP: 0.1,
	upgrades.XP_GAIN_DOWN: -0.1,
	upgrades.PICKUP_RANGE_UP: 5,
	upgrades.PICKUP_RANGE_DOWN: -5,
	upgrades.ITEMS_DISCOUNT_UP: 0.1,
	upgrades.ITEMS_DISCOUNT_DOWN: -0.1,
	upgrades.EXPLOSION_DAMAGE_UP: 10,
	upgrades.EXPLOSION_DAMAGE_DOWN: -10,
	upgrades.EXPLOSION_RADIUS_UP: 10,
	upgrades.EXPLOSION_RADIUS_DOWN: -10,
	upgrades.PIERCING_UP: 1,
	upgrades.PIERCING_DOWN: -1,
	upgrades.FREE_REROLL_UP: 1,
	upgrades.FREE_REROLL_DOWN: -1,
	upgrades.LUCK_UP: 0.1,
	upgrades.LUCK_DOWN: -0.1,
	upgrades.REMAINING_BALLS_UP: 1,
	upgrades.REMAINING_BALLS_DOWN: -1,
	upgrades.MAX_BALLS_UP: 1,
	upgrades.MAX_BALLS_DOWN: -1
}

const UPGRADE_PRICES = {
	upgrades.BALL_BOUNCE_UP: 100,
	upgrades.BALL_BOUNCE_DOWN: 100,
	upgrades.BALL_SIZE_UP: 100,
	upgrades.BALL_SIZE_DOWN: 100,
	upgrades.BALL_DAMAGE_TO_ENEMIES_UP: 100,
	upgrades.BALL_DAMAGE_TO_ENEMIES_DOWN: 100,
	upgrades.BALL_DAMAGE_TO_STRUCTURES_UP: 100,
	upgrades.BALL_DAMAGE_TO_STRUCTURES_DOWN: 100,
	upgrades.BALL_DAMAGE_TO_BOSSES_UP: 100,
	upgrades.BALL_DAMAGE_TO_BOSSES_DOWN: 100,
	upgrades.BALL_DAMAGE_UP: 100,
	upgrades.BALL_DAMAGE_DOWN: 100,
	upgrades.BALL_ELEMENTAL_DAMAGE_UP: 100,
	upgrades.BALL_ELEMENTAL_DAMAGE_DOWN: 100,
	upgrades.BALL_KNOCKBACK_UP: 100,
	upgrades.BALL_KNOCKBACK_DOWN: 100,
	upgrades.BALL_CRITICAL_HIT_CHANCE_UP: 100,
	upgrades.BALL_CRITICAL_HIT_CHANCE_DOWN: 100,
	upgrades.BALL_HEALTH_UP: 100,
	upgrades.BALL_HEALTH_DOWN: 100,
	upgrades.BALL_HEALTH_REGEN_UP: 100,
	upgrades.BALL_HEALTH_REGEN_DOWN: 100,
	upgrades.FLIPPER_SPEED_UP: 100,
	upgrades.FLIPPER_SPEED_DOWN: 100,
	upgrades.FLIPPER_PRECISION_UP: 100,
	upgrades.FLIPPER_PRECISION_DOWN: 100,
	upgrades.BUMPER_EXPANSION_SPEED_UP: 100,
	upgrades.BUMPER_EXPANSION_SPEED_DOWN: 100,
	upgrades.BUMPER_PRECISION_UP: 100,
	upgrades.BUMPER_PRECISION_DOWN: 100,
	upgrades.XP_GAIN_UP: 100,
	upgrades.XP_GAIN_DOWN: 100,
	upgrades.PICKUP_RANGE_UP: 100,
	upgrades.PICKUP_RANGE_DOWN: 100,
	upgrades.ITEMS_DISCOUNT_UP: 100,
	upgrades.ITEMS_DISCOUNT_DOWN: 100,
	upgrades.EXPLOSION_DAMAGE_UP: 100,
	upgrades.EXPLOSION_DAMAGE_DOWN: 100,
	upgrades.EXPLOSION_RADIUS_UP: 100,
	upgrades.EXPLOSION_RADIUS_DOWN: 100,
	upgrades.PIERCING_UP: 100,
	upgrades.PIERCING_DOWN: 100,
	upgrades.FREE_REROLL_UP: 100,
	upgrades.FREE_REROLL_DOWN: 100,
	upgrades.LUCK_UP: 100,
	upgrades.LUCK_DOWN: 100,
	upgrades.REMAINING_BALLS_UP: 100,
	upgrades.REMAINING_BALLS_DOWN: 100,
	upgrades.MAX_BALLS_UP: 100, 
	upgrades.MAX_BALLS_DOWN: 100
}
const UPGRADE_TYPES = {
	upgrades.BALL_BOUNCE_UP: "Ball",
	upgrades.BALL_BOUNCE_DOWN: "Ball",
	upgrades.BALL_SIZE_UP: "Ball",
	upgrades.BALL_SIZE_DOWN: "Ball",
	upgrades.BALL_DAMAGE_TO_ENEMIES_UP: "Ball",
	upgrades.BALL_DAMAGE_TO_ENEMIES_DOWN: "Ball",
	upgrades.BALL_DAMAGE_TO_STRUCTURES_UP: "Ball",
	upgrades.BALL_DAMAGE_TO_STRUCTURES_DOWN: "Ball",
	upgrades.BALL_DAMAGE_TO_BOSSES_UP: "Ball",
	upgrades.BALL_DAMAGE_TO_BOSSES_DOWN: "Ball",
	upgrades.BALL_DAMAGE_UP: "Ball",
	upgrades.BALL_DAMAGE_DOWN: "Ball",
	upgrades.BALL_ELEMENTAL_DAMAGE_UP: "Ball",
	upgrades.BALL_ELEMENTAL_DAMAGE_DOWN: "Ball",
	upgrades.BALL_KNOCKBACK_UP: "Ball",
	upgrades.BALL_KNOCKBACK_DOWN: "Ball",
	upgrades.BALL_CRITICAL_HIT_CHANCE_UP: "Ball",
	upgrades.BALL_CRITICAL_HIT_CHANCE_DOWN: "Ball",
	upgrades.BALL_HEALTH_UP: "Ball",
	upgrades.BALL_HEALTH_DOWN: "Ball",
	upgrades.BALL_HEALTH_REGEN_UP: "Ball",
	upgrades.BALL_HEALTH_REGEN_DOWN: "Ball",
	upgrades.FLIPPER_SPEED_UP: "Flipper",
	upgrades.FLIPPER_SPEED_DOWN: "Flipper",
	upgrades.FLIPPER_PRECISION_UP: "Flipper",
	upgrades.FLIPPER_PRECISION_DOWN: "Flipper",
	upgrades.BUMPER_EXPANSION_SPEED_UP: "Bumper",
	upgrades.BUMPER_EXPANSION_SPEED_DOWN: "Bumper",
	upgrades.BUMPER_PRECISION_UP: "Bumper",
	upgrades.BUMPER_PRECISION_DOWN: "Bumper",
	upgrades.XP_GAIN_UP: "General",
	upgrades.XP_GAIN_DOWN: "General",
	upgrades.PICKUP_RANGE_UP: "General",
	upgrades.PICKUP_RANGE_DOWN: "General",
	upgrades.ITEMS_DISCOUNT_UP: "General",
	upgrades.ITEMS_DISCOUNT_DOWN: "General",
	upgrades.EXPLOSION_DAMAGE_UP: "General",
	upgrades.EXPLOSION_DAMAGE_DOWN: "General",
	upgrades.EXPLOSION_RADIUS_UP: "General",
	upgrades.EXPLOSION_RADIUS_DOWN: "General",
	upgrades.PIERCING_UP: "General",
	upgrades.PIERCING_DOWN: "General",
	upgrades.FREE_REROLL_UP: "General",
	upgrades.FREE_REROLL_DOWN: "General",
	upgrades.LUCK_UP: "General",
	upgrades.LUCK_DOWN: "General",
	upgrades.REMAINING_BALLS_UP: "General",
	upgrades.REMAINING_BALLS_DOWN: "General",
	upgrades.MAX_BALLS_UP: "General",
	upgrades.MAX_BALLS_DOWN: "General"
}

const UPGRADE_SPRITES = {
	upgrades.BALL_BOUNCE_UP: "res://assets/sprites/upgrades/ball_bounce_up.png",
	upgrades.BALL_BOUNCE_DOWN: "res://assets/sprites/upgrades/ball_bounce_down.png",
	upgrades.BALL_SIZE_UP: "res://assets/sprites/upgrades/ball_size_up.png",
	upgrades.BALL_SIZE_DOWN: "res://assets/sprites/upgrades/ball_size_down.png",
	upgrades.BALL_DAMAGE_TO_ENEMIES_UP: "res://assets/sprites/upgrades/ball_damage_to_enemies_up.png",
	upgrades.BALL_DAMAGE_TO_ENEMIES_DOWN: "res://assets/sprites/upgrades/ball_damage_to_enemies_down.png",
	upgrades.BALL_DAMAGE_TO_STRUCTURES_UP: "res://assets/sprites/upgrades/ball_damage_to_structures_up.png",
	upgrades.BALL_DAMAGE_TO_STRUCTURES_DOWN: "res://assets/sprites/upgrades/ball_damage_to_structures_down.png",
	upgrades.BALL_DAMAGE_TO_BOSSES_UP: "res://assets/sprites/upgrades/ball_damage_to_bosses_up.png",
	upgrades.BALL_DAMAGE_TO_BOSSES_DOWN: "res://assets/sprites/upgrades/ball_damage_to_bosses_down.png",
	upgrades.BALL_DAMAGE_UP: "res://assets/sprites/upgrades/ball_damage_up.png",
	upgrades.BALL_DAMAGE_DOWN: "res://assets/sprites/upgrades/ball_damage_down.png",
	upgrades.BALL_ELEMENTAL_DAMAGE_UP: "res://assets/sprites/upgrades/ball_elemental_damage_up.png",
	upgrades.BALL_ELEMENTAL_DAMAGE_DOWN: "res://assets/sprites/upgrades/ball_elemental_damage_down.png",
	upgrades.BALL_KNOCKBACK_UP: "res://assets/sprites/upgrades/ball_knockback_up.png",
	upgrades.BALL_KNOCKBACK_DOWN: "res://assets/sprites/upgrades/ball_knockback_down.png",
	upgrades.BALL_CRITICAL_HIT_CHANCE_UP: "res://assets/sprites/upgrades/ball_critical_hit_chance_up.png",
	upgrades.BALL_CRITICAL_HIT_CHANCE_DOWN: "res://assets/sprites/upgrades/ball_critical_hit_chance_down.png",
	upgrades.BALL_HEALTH_UP: "res://assets/sprites/upgrades/ball_health_up.png",
	upgrades.BALL_HEALTH_DOWN: "res://assets/sprites/upgrades/ball_health_down.png",
	upgrades.BALL_HEALTH_REGEN_UP: "res://assets/sprites/upgrades/ball_health_regen_up.png",
	upgrades.BALL_HEALTH_REGEN_DOWN: "res://assets/sprites/upgrades/ball_health_regen_down.png",
	upgrades.FLIPPER_SPEED_UP: "res://assets/sprites/upgrades/flipper_speed_up.png",
	upgrades.FLIPPER_SPEED_DOWN: "res://assets/sprites/upgrades/flipper_speed_down.png",
	upgrades.FLIPPER_PRECISION_UP: "res://assets/sprites/upgrades/flipper_precision_up.png",
	upgrades.FLIPPER_PRECISION_DOWN: "res://assets/sprites/upgrades/flipper_precision_down.png",
	upgrades.BUMPER_EXPANSION_SPEED_UP: "res://assets/sprites/upgrades/bumper_expansion_speed_up.png",
	upgrades.BUMPER_EXPANSION_SPEED_DOWN: "res://assets/sprites/upgrades/bumper_expansion_speed_down.png",
	upgrades.BUMPER_PRECISION_UP: "res://assets/sprites/upgrades/bumper_precision_up.png",
	upgrades.BUMPER_PRECISION_DOWN: "res://assets/sprites/upgrades/bumper_precision_down.png",
	upgrades.XP_GAIN_UP: "res://assets/sprites/upgrades/xp_gain_up.png",
	upgrades.XP_GAIN_DOWN: "res://assets/sprites/upgrades/xp_gain_down.png",
	upgrades.PICKUP_RANGE_UP: "res://assets/sprites/upgrades/pickup_range_up.png",
	upgrades.PICKUP_RANGE_DOWN: "res://assets/sprites/upgrades/pickup_range_down.png",
	upgrades.ITEMS_DISCOUNT_UP: "res://assets/sprites/upgrades/items_discount_up.png",
	upgrades.ITEMS_DISCOUNT_DOWN: "res://assets/sprites/upgrades/items_discount_down.png",
	upgrades.EXPLOSION_DAMAGE_UP: "res://assets/sprites/upgrades/explosion_damage_up.png",
	upgrades.EXPLOSION_DAMAGE_DOWN: "res://assets/sprites/upgrades/explosion_damage_down.png",
	upgrades.EXPLOSION_RADIUS_UP: "res://assets/sprites/upgrades/explosion_radius_up.png",
	upgrades.EXPLOSION_RADIUS_DOWN: "res://assets/sprites/upgrades/explosion_radius_down.png",
	upgrades.PIERCING_UP: "res://assets/sprites/upgrades/piercing_up.png",
	upgrades.PIERCING_DOWN: "res://assets/sprites/upgrades/piercing_down.png",
	upgrades.FREE_REROLL_UP: "res://assets/sprites/upgrades/free_reroll_up.png",
	upgrades.FREE_REROLL_DOWN: "res://assets/sprites/upgrades/free_reroll_down.png",
	upgrades.LUCK_UP: "res://assets/sprites/upgrades/luck_up.png",
	upgrades.LUCK_DOWN: "res://assets/sprites/upgrades/luck_down.png",
	upgrades.REMAINING_BALLS_UP: "res://assets/sprites/upgrades/remaining_balls_up.png",
	upgrades.REMAINING_BALLS_DOWN: "res://assets/sprites/upgrades/remaining_balls_down.png",
	upgrades.MAX_BALLS_UP: "res://assets/sprites/upgrades/max_balls_up.png",
	upgrades.MAX_BALLS_DOWN: "res://assets/sprites/upgrades/max_balls_down.png"
}

func get_upgrade_key_from_name(upgrade_name: String) -> int:
	for key in UPGRADE_NAMES.keys():
		if UPGRADE_NAMES[key] == upgrade_name:
			return key
	return -1  
